apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "symfony-demo.fullname" . }}
data:
  APP_ENV: "prod"
  APP_DEBUG: "0"

  {{- range $key, $val := $.Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
