apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "symfony-demo.fullname" . }}
  labels:
      {{- include "symfony-demo.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.alb_group_name | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.hostname }}.{{ .Values.global.root_domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "symfony-demo.fullname" . }}
                port:
                  number: 80
