apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "symfony-demo.fullname" . }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secret.awsArn }}"
        objectType: "secretsmanager"
        jmesPath:
        {{- range .Values.secret.vars }}
          - path: {{ . }}
            objectAlias: {{ . | quote }}
        {{- end }}
  # still need to map each key-value manually https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/529
  secretObjects:
    - secretName: {{ include "symfony-demo.fullname" . }}
      type: Opaque
      data:
        {{- range .Values.secret.vars }}
        - objectName: {{ . | quote }}
          key: {{ . | quote }}
        {{- end }}
