apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: secrets-store-csi-driver-provider-aws
  name: {{ .Values.serviceAccountName }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::562414170838:role/EKS_SSM_CSI_DriverRole
